### PR TITLE
Feature/ssm install

### PR DESCRIPTION
**Pull request by igorkotof**
- Added ICMK installation of Session Manager Plugin on MacOS or any GNU/Linux
  - Download
  - Install
  - Cleanup
  - Verification

**NOTE**: Should be tested on MacOS by someone from the team 

Testing:
[asciicast](https://asciinema.org/a/eyAKXKOcMP49b3o130LjuIE2l)

### CODE REVIEW

**Comment by igorkotof** [comment]
[Update SSM-bastion tunnel in terraform-aws-ec2-bastion module](https://trello.com/c/KPejQkcl/141-update-ssm-bastion-tunnel-in-terraform-aws-ec2-bastion-module)

**Comment by igorkotof** [comment]
@AutomationD any ideas how we can hide the outputs from download and installation? :)

**Comment by AutomationD** [comment]
> @AutomationD any ideas how we can hide the outputs from download and installation? :)

Let's start with `curl -s` and see if that is going to be enough.
As an option, you can add `@` in front of a command to hide it from the make output

**Comment by igorkotof** [comment]
> As an option, you can add `@` in front of a command to hide it from the make output

@AutomationD I tried @ - it's hide a command but not output

**Comment by AutomationD** [comment]
MacOS Test:

```
 make ssm-plugin                                                             
awk: fatal: cannot open file `/etc/*-release' for reading: No such file or directory
/bin/sh: lscpu: command not found
awk: fatal: cannot open file `/etc/*-release' for reading: No such file or directory
awk: fatal: cannot open file `/etc/*-release' for reading: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4963k  100 4963k    0     0  2536k      0  0:00:01  0:00:01 --:--:-- 2535k
Archive:  sessionmanager-bundle.zip
   creating: sessionmanager-bundle/
 extracting: sessionmanager-bundle/VERSION
  inflating: sessionmanager-bundle/LICENSE
  inflating: sessionmanager-bundle/seelog.xml.template
  inflating: sessionmanager-bundle/install
   creating: sessionmanager-bundle/bin/
  inflating: sessionmanager-bundle/bin/session-manager-plugin
awk: fatal: cannot open file `/etc/*-release' for reading: No such file or directory
awk: fatal: cannot open file `/etc/*-release' for reading: No such file or directory
```

I think the issue is that `$(shell )` is evaluated before actual task execution. My suggestion would be to shift all shell execution inside of your conditional, so the command is there, but it's not actually executed.

**Review by AutomationD — APPROVED** [review]
Looks Good

**Pull request merged**
