### PR TITLE
shell which session-manager-plugin

### PR DESCRIPTION
**Pull request by igorkotof**
Fixed the issue: If ssm plugin is not installed there is an error coming from `make icmk.update`

### CODE REVIEW

**Comment by igorkotof** [comment]
[If ssm plugin is not installed there is an error coming from make](https://trello.com/c/q6IRRUIR/157-if-ssm-plugin-is-not-installed-there-is-an-error-coming-from-make)

**Comment by igorkotof** [comment]
[Odd error when installing ssm plugin](https://trello.com/c/q5lfWHqw/158-odd-error-when-installing-ssm-plugin)

**Review by AutomationD — APPROVED** [review]
Looks good if this has been tested.
Maybe we should add another test to github workflows to test a missing session-manager situation

**Comment by igorkotof** [comment]
> Looks good if this has been tested.
> Maybe we should add another test to github workflows to test a missing session-manager situation

You know it 100% works, I tested, `which` nothing returns if a tool not installed. I'm not sure about additional test to github workflows

**Pull request merged**
