### PR TITLE
Add target: ecs-public.login

### PR DESCRIPTION
**Pull request by igorkotof**
- Add possibility to ecs.login target to work with public ECR
- Upgraded aws-cli docker version

### CODE REVIEW

**Comment by igorkotof** [comment]
[ecs-public.login target](https://trello.com/c/h4kuofcj/285-ecs-publiclogin-target)

**Review by gloovers — APPROVED** [review]
LGTM

**Review by AutomationD — CHANGES_REQUESTED** [review]
I'm wondering if we could do something like
(pseudobash:)

```
AWS_CLI_ECR_LOGIN ?= $(shell if $(DOCKER_REGISTRY) == "public"; then echo "get-public-login"; else echo "get-login-password")`
```
and then
```
$(AWS) $(AWS_CLI_ECR_LOGIN) ...
```

**Comment by igorkotof** [comment]
> I'm wondering if we could do something like
> (pseudobash:)
> 
> ```
> AWS_CLI_ECR_LOGIN ?= $(shell if $(DOCKER_REGISTRY) == "public"; then echo "get-public-login"; else echo "get-login-password")`
> ```
> 
> and then
> 
> ```
> $(AWS) $(AWS_CLI_ECR_LOGIN) ...
> ```

@AutomationD improved and tested in SK

**Review by AutomationD — APPROVED** [review]

**Pull request merged**
